apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lpnode.fullname" . }}
  labels:
    app: {{ include "lpnode.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "lpnode.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "lpnode.fullname" . }}
    spec:
      containers:
      - name: {{ include "lpnode.fullname" . }}
        image: {{ .Values.image.name }}
        ports:
          - containerPort: 18081
        env:
          - name: REDIS_HOST
            value: "lpnode-db-redis-master"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lpnode-db-redis
                key: redis-password
          - name: NODE_ENV
            value: "{{ .Values.lpconfig.market_env }}"
          - name: LP_NODE_DATA_MONGO_URL
            value: "lpnode-db-mongodb"
          - name: LP_MARKET_SERVICE_URL
            value: "lpnode-market"
          - name: KUBERNETES_SERVICE_PORT_HTTPS
            value: 1000

# ENV LP_NODE_DATA_MONGO_URL=mongodb://root:123456@192.168.50.201:27017/lp_store?authSource=admin

