apiVersion: v1
kind: Service
metadata:
  name: {{ include "lpnode.fullname" . }}-server
spec:
  selector:
    app: {{ include "lpnode.fullname" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: {{ include "lpnode.fullname" . }}-api
      port: 18081
      targetPort: 18081